---
name: Tado Optimizer
version: 1.0.2
slug: tado_optimizer
description: Home Battery Prediction and Control
url: https://github.com/charlie-chester/tado_optimizer
codenotary: m.chester@me.com
ingress: True
ingress_port: 5052
ingress_root: "/"
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
hassio_api: true
hassio_role: admin
auth_api: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
options:
  longitude: "Longitude"
  latitude: "Latitude"
  open_weather_api: "Open Weather API Key"
schema:
  longitude: str
  latitude: str
  open_weather_api: str
  log_level:
    type: str
    default: "info"
    values:
      - trace
      - debug
      - info
      - notice
      - warning
      - error
      - fatal
